const serverURL = "http://api.drliveseyservice.pagekite.me/api/";

const anomaliesMock = {
  anomalies: [
    {
      id: 0,
      latitude: 52.567157,
      longitude: 39.507682,
      opening_date: "2002-10-08",
      closing_date: "2002-10-10",
      district_name: "string",
      address: "string",
      fault_name: "string",
      management_company_name: "string",
      service_organization_name: "string",
      urgency_category_name: "string",
      anomaly_category: "string",
    },
    {
      id: 1,
      latitude: 53.746521,
      longitude: 91.416848,
      opening_date: "2002-10-08",
      closing_date: "2002-10-10",
      district_name: "string",
      address: "string",
      fault_name: "string",
      management_company_name: "string",
      service_organization_name: "string",
      urgency_category_name: "string",
      anomaly_category: "string",
    },
    {
      id: 2,
      latitude: 53.746521,
      longitude: 91.416848,
      opening_date: "2002-10-08",
      closing_date: "2002-10-10",
      district_name: "string",
      address: "string",
      fault_name: "string",
      management_company_name: "string",
      service_organization_name: "string",
      urgency_category_name: "string",
      anomaly_category: "string",
    },
    {
      id: 3,
      latitude: 53.746521,
      longitude: 91.416848,
      opening_date: "2002-10-08",
      closing_date: "2002-10-10",
      district_name: "string",
      address: "string",
      fault_name: "string",
      management_company_name: "string",
      service_organization_name: "string",
      urgency_category_name: "string",
      anomaly_category: "string",
    },
    {
      id: 4,
      latitude: 53.746521,
      longitude: 91.416848,
      opening_date: "2002-10-08",
      closing_date: "2002-10-10",
      district_name: "string",
      address: "string",
      fault_name: "string",
      management_company_name: "string",
      service_organization_name: "string",
      urgency_category_name: "string",
      anomaly_category: "string",
    },
    {
      id: 5,
      latitude: 53.746521,
      longitude: 91.416848,
      opening_date: "2002-10-08",
      closing_date: "2002-10-10",
      district_name: "string",
      address: "string",
      fault_name: "string",
      management_company_name: "string",
      service_organization_name: "string",
      urgency_category_name: "string",
      anomaly_category: "string",
    },
    {
      id: 6,
      latitude: 53.746521,
      longitude: 91.416848,
      opening_date: "2002-10-08",
      closing_date: "2002-10-10",
      district_name: "string",
      address: "string",
      fault_name: "string",
      management_company_name: "string",
      service_organization_name: "string",
      urgency_category_name: "string",
      anomaly_category: "string",
    },
    {
      id: 7,
      latitude: 53.746521,
      longitude: 91.416848,
      opening_date: "2002-10-08",
      closing_date: "2002-10-10",
      district_name: "string",
      address: "string",
      fault_name: "string",
      management_company_name: "string",
      service_organization_name: "string",
      urgency_category_name: "string",
      anomaly_category: "string",
    },
    {
      id: 8,
      latitude: 53.746521,
      longitude: 91.416848,
      opening_date: "2002-10-08",
      closing_date: "2002-10-10",
      district_name: "string",
      address: "string",
      fault_name: "string",
      management_company_name: "string",
      service_organization_name: "string",
      urgency_category_name: "string",
      anomaly_category: "string",
    },
    {
      id: 9,
      latitude: 53.546521,
      longitude: 91.416848,
      opening_date: "2002-10-08",
      closing_date: "2002-10-10",
      district_name: "string",
      address: "string",
      fault_name: "string",
      management_company_name: "string",
      service_organization_name: "string",
      urgency_category_name: "string",
      anomaly_category: "string",
    },
  ],
};

const pointsMock = [
  { date: "Feb 10 2016", percent: 94.27 },
  { date: "Feb 11 2016", percent: 93.7 },
  { date: "Feb 12 2016", percent: 93.99 },
  { date: "Feb 16 2016", percent: 96.64 },
  { date: "Feb 17 2016", percent: 98.12 },
  { date: "Feb 18 2016", percent: 96.26 },
  { date: "Feb 19 2016", percent: 96.04 },
  { date: "Feb 22 2016", percent: 96.88 },
  { date: "Feb 23 2016", percent: 94.69 },
  { date: "Feb 24 2016", percent: 96.1 },
  { date: "Feb 25 2016", percent: 96.76 },
  { date: "Feb 26 2016", percent: 96.91 },
  { date: "Feb 29 2016", percent: 96.69 },
  { date: "Mar 01 2016", percent: 50 },
  { date: "Mar 02 2016", percent: 50 },
  { date: "Mar 03 2016", percent: 30 },
  { date: "Mar 04 2016", percent: 35 },
  { date: "Mar 07 2016", percent: 20 },
  { date: "Mar 08 2016", percent: 40 },
  { date: "Mar 09 2016", percent: 45 },
  { date: "Mar 10 2016", percent: 50 },
  { date: "Mar 11 2016", percent: 50 },
  { date: "Mar 12 2016", percent: 30 },
  { date: "Mar 13 2016", percent: 35 },
  { date: "Mar 14 2016", percent: 20 },
  { date: "Mar 15 2016", percent: 40 },
  { date: "Mar 16 2016", percent: 45 },
  { date: "Mar 17 2016", percent: 50 },
  { date: "Mar 18 2016", percent: 50 },
  { date: "Mar 19 2016", percent: 30 },
  { date: "Mar 20 2016", percent: 35 },
  { date: "Mar 21 2016", percent: 20 },
  { date: "Mar 22 2016", percent: 40 },
  { date: "Mar 23 2016", percent: 45 },
];

const infoMock = {
  requests: [
    {
      number: 0,
      "opening date": "string",
      "closing date": "string",
      "district name": "string",
      address: "string",
      "fault name": "string",
      "management company name": "string",
      "urgency category name": "string",
      feedback: "string",
      description: "string",
      effectiveness: "string",
      work: "string",
    },
    {
      number: 0,
      "opening date": "string",
      "closing date": "string",
      "district name": "string",
      address: "string",
      "fault name": "string",
      "management company name": "string",
      "urgency category name": "string",
      feedback: "string",
      description: "string",
      effectiveness: "string",
      work: "string",
    },
  ],
};

export { serverURL, anomaliesMock, pointsMock, infoMock };
